<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [27]:
def matrix_mul(A, B):
    a_m = len(A)
    a_n = len(A[0])
    b_m = len(B)
    b_n = len(B[0])
    if a_n == b_m:
      c = [[0 for x in range(b_n)] for y in range(a_m)]
      for i in range(len(A)):
        for j in range(len(B[0])):
          for k in range(len(B)):
            c[i][j] += A[i][k] * B[k][j]
      return c
    else:
      print('Not possible')

A = [[1, 3, 4], [2, 5, 7], [5, 9, 6]]
B = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
matrix_mul(A, B)

[[1, 3, 4], [2, 5, 7], [5, 9, 6]]

<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [26]:
from random import uniform

def pick_a_number_from_list(A):
  sum_A = sum(A)
  normalized_A = [ele/sum_A for ele in A]
  cum_sum = []
  sum_i = 0
  for i in normalized_A:
    sum_i += i
    cum_sum.append(sum_i)
  r = uniform(0,1) 
  number = 0
  for index in range(len(cum_sum)):
    if (r>=cum_sum[index] and r<cum_sum[index+1]):
      return A[index+1]
  return number


def sampling_based_on_magnitued():
    A = [1, 5, 27, 6, 13, 28, 100, 45, 10, 79]
    a = dict()
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        if number not in a:
            a[number] = 1
        else:
            a[number]+=1
    return a

sampling_based_on_magnitued()

{0: 1, 5: 2, 6: 2, 10: 3, 27: 6, 28: 10, 45: 11, 79: 31, 100: 33}

<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [28]:
import re
def replace_digits(String):
  return len(re.sub('\D','', String))*'#'

replace_digits('#2a$#b%c%561#')

'####'

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [29]:
def display_dash_board(students, marks):
  stud_marks = {students[i]: marks[i] for i in range(len(students))}
  top_5_students = sorted(stud_marks.items(), key = lambda item: item[1], reverse=True)[:5]
  least_5_students = sorted(stud_marks.items(),key = lambda item: item[1])[:5]
  sorted_dict = sorted(stud_marks.items(), key = lambda item: item[1])
  students_within_25_and_75 = []
  max_mark = max(stud_marks.values())
  min_mark = min(stud_marks.values())
  diff     = max_mark - min_mark
  pre_25   = diff*0.25
  pre_75   = diff*0.75
  for i in sorted(stud_marks.items(),key=lambda item: item[1]):
    if(i[1]>pre_25 and i[1]<pre_75):
      students_within_25_and_75.append((i[0],i[1]))
  print("Top 5")
  [print(key,':',value) for key, value in top_5_students]
  print("\n")
  print("Least 5")
  [print(key,':',value) for key, value in least_5_students]
  print("\n")
  print("25-75 Percentile")
  [print(key,':',value) for key, value in students_within_25_and_75]


students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
display_dash_board(students, marks)

Top 5
student8 : 98
student10 : 80
student2 : 78
student5 : 48
student7 : 47


Least 5
student3 : 12
student4 : 14
student9 : 35
student6 : 43
student1 : 45


25-75 Percentile
student9 : 35
student6 : 43
student1 : 45
student7 : 47
student5 : 48


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [30]:
import math

def closest_points_to_p(S, P):
  closest_points = []
  for point in S:
    denominator = math.sqrt((point[0] ** 2) + (point[1] ** 2)) * math.sqrt((P[0] ** 2) + (P[1] ** 2))
    numerator = point[0] * P[0] + point[1] * P[1]
    if denominator != 0:
      cosine_dist = math.acos(numerator / denominator)
      closest_points.append((cosine_dist, point))

  results = [x[1] for x in sorted(closest_points,key=lambda x: x[0])[:5]]
  return results

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
closest_points_to_p(S, P)

[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]

<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [31]:
def i_am_the_one(red,blue,line):
  red_sign = -1

  if eval(line.replace('x', '*%s' %red[0][0]).replace('y', '*%s' %red[0][1])) > 0:
    red_sign = 1
  
  for r_point in red:
    if eval(line.replace('x', '*%s' %r_point[0]).replace('y', '*%s' %r_point[1])) < 0 and red_sign == 1:
      return 'NO'
          
    if eval(line.replace('x', '*%s' %r_point[0]).replace('y', '*%s' %r_point[1])) > 0 and red_sign == -1:
      return 'NO'
    

  blue_sign = -1*red_sign

  for b_point in blue:
    if eval(line.replace('x', '*%s' %b_point[0]).replace('y', '*%s' %b_point[1])) < 0 and blue_sign == 1:
      return 'NO'

    if eval(line.replace('x', '*%s' %b_point[0]).replace('y', '*%s' %b_point[1])) > 0 and blue_sign == -1:
      return 'NO'
    
  return 'YES'

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) 

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [32]:
def curve_smoothing(string):
  string_list = string.split(',')
  digit_index = [string_list.index(x) for x in string_list if x!='_']
  digit_index.append(len(string_list)-1)

  start = 0
  for i in digit_index:
    digit_sum = int(string_list[i]) if string_list[i] != '_' else 0
    digit_sum += int(string_list[start]) if string_list[start] != '_' and start != i else 0 

    sub_value = digit_sum // (i-start+1)

    string_list = [sub_value if start <= x <= i else string_list[x] for x in range(len(string_list))]
    start = i
  
  return string_list




S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

[10, 10, 12, 12, 12, 12, 4, 4, 4]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [33]:
def compute_conditional_probabilites(A):
  fs_count = dict()
  for i in A:
    dict_key = i[0] + i[1]
    fs_count[dict_key] = 0

  s_count = {'S1':0,'S2':0,'S3':0}

  for i in A:
    fs_inter = i[0]+i[1]
    fs_count[fs_inter] += 1

    s_item = i[1]
    s_count[s_item] += 1

  print('{0:c}. P(F=F1|S==S1) = {F1S1}/{S1}, P(F=F1|S==S2) = {F1S2}/{S2}, P(F=F1|S==S3) = {F1S3}/{S3}'.format(97, F1S1=fs_count.get('F1S1', 0),S1=s_count['S1'],F1S2=fs_count.get('F1S2', 0),S2=s_count['S2'],F1S3=fs_count.get('F1S3', 0),S3=s_count['S3']))

  print('{0:c}. P(F=F2|S==S1) = {F2S1}/{S1}, P(F=F2|S==S2) = {F2S2}/{S2}, P(F=F2|S==S3) = {F2S3}/{S3}'.format(98, F2S1=fs_count.get('F2S1', 0),S1=s_count['S1'],F2S2=fs_count.get('F2S2', 0),S2=s_count['S2'],F2S3=fs_count.get('F2S3', 0),S3=s_count['S3']))

  print('{0:c}. P(F=F3|S==S1) = {F3S1}/{S1}, P(F=F3|S==S2) = {F3S2}/{S2}, P(F=F3|S==S3) = {F3S3}/{S3}'.format(99, F3S1=fs_count.get('F3S1', 0),S1=s_count['S1'],F3S2=fs_count.get('F3S2', 0),S2=s_count['S2'],F3S3=fs_count.get('F3S3', 0),S3=s_count['S3']))

  print('{0:c}. P(F=F4|S==S1) = {F4S1}/{S1}, P(F=F4|S==S2) = {F4S2}/{S2}, P(F=F4|S==S3) = {F4S3}/{S3}'.format(100, F4S1=fs_count.get('F4S1', 0),S1=s_count['S1'],F4S2=fs_count.get('F4S2', 0),S2=s_count['S2'],F4S3=fs_count.get('F4S3', 0),S3=s_count['S3']))

  print('{0:c}. P(F=F5|S==S1) = {F5S1}/{S1}, P(F=F5|S==S2) = {F5S2}/{S2}, P(F=F5|S==S3) = {F5S3}/{S3}'.format(101, F5S1=fs_count.get('F5S1', 0),S1=s_count['S1'],F5S2=fs_count.get('F5S2', 0),S2=s_count['S2'],F5S3=fs_count.get('F5S3', 0),S3=s_count['S3']))

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

a. P(F=F1|S==S1) = 1/4, P(F=F1|S==S2) = 1/3, P(F=F1|S==S3) = 0/3
b. P(F=F2|S==S1) = 1/4, P(F=F2|S==S2) = 1/3, P(F=F2|S==S3) = 1/3
c. P(F=F3|S==S1) = 0/4, P(F=F3|S==S2) = 1/3, P(F=F3|S==S3) = 1/3
d. P(F=F4|S==S1) = 1/4, P(F=F4|S==S2) = 0/3, P(F=F4|S==S3) = 1/3
e. P(F=F5|S==S1) = 1/4, P(F=F5|S==S2) = 0/3, P(F=F5|S==S3) = 0/3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [34]:
def string_features(S1, S2):
  s1_split = set(S1.split(" "))
  s2_split = set(S2.split(" "))

  a = len(s1_split.intersection(s2_split))
  b = s1_split - s2_split
  c = s2_split - s1_split

  return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(a,'\n',b,'\n',c)

7 
 {'first', '5', 'F'} 
 {'3', 'second', 'S'}


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [35]:
from math import log

def compute_log_loss(A):
  summation = 0
  for i in A:
    summation += (i[0]*log(i[1],10) + ((1-i[0])*log(1-i[1],10)))

  loss = -1 * summation / len(A)
  return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
